import { prisma } from '@/lib/db'
import { getCurrentUser } from '@/lib/session'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import PageHeader from '@/components/PageHeader'
import Badge, { workOrderStatusVariant, priorityVariant } from '@/components/Badge'
import PMGenerateButton from '@/components/PMGenerateButton'
import PMToggleButton from '@/components/PMToggleButton'
import DeletePMScheduleButton from '@/components/DeletePMScheduleButton'
import { fmt, daysUntil } from '@/lib/utils'

const freqLabels: Record<string, string> = {
  DAILY: 'Daily', WEEKLY: 'Weekly', MONTHLY: 'Monthly',
  QUARTERLY: 'Quarterly', YEARLY: 'Yearly',
}
const woStatusLabels: Record<string,string> = {
  OPEN:'Open', IN_PROGRESS:'In Progress', ON_HOLD:'On Hold', COMPLETED:'Completed', CANCELLED:'Cancelled',
}

export default async function PMDetailPage({
  params,
}: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const user = await getCurrentUser()
  const canEdit = user?.role === 'ADMIN' || user?.role === 'MANAGER'

  const schedule = await prisma.maintenanceSchedule.findUnique({
    where: { id },
    include: {
      asset: {
        include: {
          location: { select: { name: true } },
          category: { select: { name: true } },
        },
      },
      location: { select: { id: true, name: true } },
      createdBy: { select: { name: true } },
      procedures: {
        include: {
          procedure: {
            select: { id: true, name: true, description: true },
          },
        },
        orderBy: { sortOrder: 'asc' },
      },
    },
  })

  if (!schedule) notFound()

  // Query work orders generated by this specific PM schedule, falling back to asset's PREVENTIVE work orders
  const workOrders = await prisma.workOrder.findMany({
    where: {
      OR: [
        { maintenanceScheduleId: schedule.id },
        ...(schedule.assetId ? [{ assetId: schedule.assetId, type: 'PREVENTIVE' as const }] : []),
      ]
    },
    include: { assignedTo: { select: { name: true } } },
    orderBy: { createdAt: 'desc' },
    take: 20,
  })

  const days    = daysUntil(schedule.nextDueDate)
  const overdue = schedule.isActive && days < 0
  const canGenerate = schedule.isActive && days <= 0

  const targetName = schedule.asset?.name ?? schedule.location?.name ?? 'General'

  return (
    <div className="p-6 max-w-6xl mx-auto">
      <div className="mb-1">
        <Link href="/preventive-maintenance" className="text-sm text-gray-400 hover:text-gray-600">
          ← Back to PM schedules
        </Link>
      </div>
      <PageHeader
        title={schedule.title}
        subtitle={`${targetName} · Every ${schedule.interval > 1 ? `${schedule.interval} ` : ''}${freqLabels[schedule.frequency].toLowerCase()}`}
        action={
          canEdit ? (
            <Link href={`/preventive-maintenance/${schedule.id}/edit`} className="btn-secondary text-sm">
              Edit schedule
            </Link>
          ) : undefined
        }
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left */}
        <div className="space-y-5">
          {/* Next due + generate */}
          <div className="bg-white rounded-xl border border-gray-200 p-5">
            <h2 className="font-semibold text-gray-900 text-sm mb-3">Next due date</h2>
            <p className={`text-2xl font-bold mb-1 ${overdue ? 'text-red-600' : 'text-gray-900'}`}>
              {fmt(schedule.nextDueDate)}
            </p>
            <p className={`text-sm mb-4 ${overdue ? 'text-red-500' : 'text-gray-400'}`}>
              {overdue
                ? `${Math.abs(days)} day${Math.abs(days) !== 1 ? 's' : ''} overdue`
                : days === 0
                ? 'Due today'
                : `In ${days} day${days !== 1 ? 's' : ''}`}
            </p>

            {canEdit && (
              <PMGenerateButton
                scheduleId={schedule.id}
                assetName={targetName}
                scheduleName={schedule.title}
                canGenerate={canGenerate}
                isOverdue={overdue}
              />
            )}
          </div>

          {/* Details */}
          <div className="bg-white rounded-xl border border-gray-200 p-5">
            <h2 className="font-semibold text-gray-900 text-sm mb-4">Schedule details</h2>
            <dl className="space-y-3">
              {[
                { label: 'Status',     value: (
                  <Badge label={schedule.isActive ? 'Active' : 'Inactive'} variant={schedule.isActive ? 'green' : 'gray'} />
                )},
                ...(schedule.asset ? [
                  { label: 'Asset',      value: (
                    <Link href={`/assets/${schedule.asset.id}`} className="text-blue-600 hover:underline text-xs">
                      {schedule.asset.name}
                    </Link>
                  )},
                  { label: 'Asset code', value: schedule.asset.assetCode ?? '—' },
                  { label: 'Location',   value: schedule.asset.location?.name ?? '—' },
                  { label: 'Category',   value: schedule.asset.category?.name ?? '—' },
                ] : []),
                ...(schedule.location ? [
                  { label: 'Location', value: schedule.location.name },
                  { label: 'Scope', value: schedule.locationScope === 'ALL_ASSETS' ? 'All Assets Checklist' : 'General Maintenance' },
                ] : []),
                { label: 'Frequency',  value: `Every ${schedule.interval > 1 ? `${schedule.interval} ` : ''}${freqLabels[schedule.frequency].toLowerCase()}` },
                { label: 'Created by', value: schedule.createdBy?.name ?? '—' },
                { label: 'Created',    value: fmt(schedule.createdAt) },
              ].map(row => (
                <div key={row.label} className="flex justify-between items-center gap-4">
                  <dt className="text-xs text-gray-400 flex-shrink-0">{row.label}</dt>
                  <dd className="text-xs text-gray-900 font-medium text-right">{row.value}</dd>
                </div>
              ))}
            </dl>
          </div>

          {/* Description */}
          {schedule.description && (
            <div className="bg-white rounded-xl border border-gray-200 p-5">
              <h2 className="font-semibold text-gray-900 text-sm mb-2">Description</h2>
              <p className="text-sm text-gray-600 leading-relaxed">{schedule.description}</p>
            </div>
          )}

          {/* Procedures */}
          {schedule.procedures && schedule.procedures.length > 0 && (
            <div className="bg-white rounded-xl border border-gray-200 p-5">
              <h2 className="font-semibold text-gray-900 text-sm mb-3">Attached Procedures</h2>
              <div className="space-y-2">
                {schedule.procedures.map((cp: any) => (
                  <div key={cp.procedure.id} className="p-3 border border-gray-150 rounded-lg bg-gray-50/50 hover:bg-gray-50 transition-colors">
                    <p className="text-xs font-semibold text-gray-800">{cp.procedure.name}</p>
                    {cp.procedure.description && (
                      <p className="text-[10px] text-gray-500 mt-0.5">{cp.procedure.description}</p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Toggle active */}
          {canEdit && (
            <div className="bg-white rounded-xl border border-gray-200 p-5">
              <h2 className="font-semibold text-gray-900 text-sm mb-2">Schedule active</h2>
              <p className="text-xs text-gray-500 mb-3">
                {schedule.isActive
                  ? 'This schedule is active. Deactivating will stop new WOs from being generated.'
                  : 'This schedule is inactive. Activate to resume WO generation.'}
              </p>
              <PMToggleButton scheduleId={schedule.id} isActive={schedule.isActive} />
            </div>
          )}

          {/* Danger zone */}
          {user?.role === 'ADMIN' && (
            <div className="bg-white rounded-xl border border-red-100 p-5">
              <h2 className="font-semibold text-red-700 text-sm mb-2">Danger zone</h2>
              <p className="text-xs text-gray-500 mb-3">
                Deleting this preventive maintenance schedule will permanently remove it. Future work orders will not be generated automatically.
              </p>
              <DeletePMScheduleButton scheduleId={schedule.id} scheduleName={schedule.title} />
            </div>
          )}
        </div>

        {/* Right: generated WO history */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-xl border border-gray-200">
            <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100">
              <h2 className="font-semibold text-gray-900 text-sm">
                Generated work orders
                <span className="ml-2 text-gray-400 font-normal">({workOrders.length})</span>
              </h2>
            </div>
            {workOrders.length === 0 ? (
              <div className="py-16 text-center">
                <p className="text-sm text-gray-400">No work orders generated yet</p>
                {canGenerate && canEdit && (
                  <p className="text-xs text-gray-400 mt-1">Click "Generate work order" to create the first one</p>
                )}
              </div>
            ) : (
              <div className="divide-y divide-gray-50">
                {workOrders.map((wo: any) => (
                  <Link
                    key={wo.id}
                    href={`/work-orders/${wo.id}`}
                    className="flex items-center gap-4 px-5 py-3.5 hover:bg-gray-50 transition-colors"
                  >
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-gray-900 truncate">{wo.title}</p>
                      <p className="text-xs text-gray-400">
                        {wo.woNumber}{wo.assignedTo ? ` · ${wo.assignedTo.name}` : ''}
                        {wo.dueDate ? ` · Due ${fmt(wo.dueDate)}` : ''}
                      </p>
                    </div>
                    <div className="flex gap-2 flex-shrink-0">
                      <Badge label={wo.priority} variant={priorityVariant(wo.priority)} />
                      <Badge label={woStatusLabels[wo.status]} variant={workOrderStatusVariant(wo.status)} />
                    </div>
                  </Link>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
