import { prisma } from '@/lib/db'
import { getCurrentUser } from '@/lib/session'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import PageHeader from '@/components/PageHeader'
import Badge, { workOrderStatusVariant, priorityVariant } from '@/components/Badge'
import { WO_STATUS_LABELS } from '@/lib/work-order-status'
import PMGenerateButton from '@/components/PMGenerateButton'
import PMToggleButton from '@/components/PMToggleButton'
import DeletePMScheduleButton from '@/components/DeletePMScheduleButton'
import PMCopyButton from '@/components/PMCopyButton'
import PMPreviewPanel from '@/components/PMPreviewPanel'
import { fmt, daysUntil } from '@/lib/utils'
import { getUserLocationIds } from '@/lib/access-control'

const freqLabels: Record<string, string> = {
  DAILY: 'Daily', WEEKLY: 'Weekly', MONTHLY: 'Monthly',
  QUARTERLY: 'Quarterly', YEARLY: 'Yearly',
}
const woStatusLabels = WO_STATUS_LABELS

export default async function PMDetailPage({
  params,
}: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const user = await getCurrentUser()
  const canEdit = user?.role === 'ADMIN' || user?.role === 'MANAGER'

  const schedule = await prisma.maintenanceSchedule.findUnique({
    where: { id },
    include: {
      asset: {
        include: {
          location: { select: { name: true } },
          category: { select: { name: true } },
        },
      },
      assets: {
        include: {
          asset: {
            include: {
              location: { select: { name: true } },
              category: { select: { name: true } },
            },
          },
        },
      },
      location: { select: { id: true, name: true } },
      createdBy: { select: { name: true } },
      woAssignedTo: { select: { name: true } },
      woTeam: { select: { name: true } },
      woCategory: { select: { name: true } },
      tasks: {
        orderBy: { order: 'asc' },
        include: { assignedTo: { select: { name: true } } },
      },
    },
  })

  if (!schedule) notFound()

  // Plant isolation: page-level view guard (cross-plant schedules render as 404)
  if (user) {
    const allowedIds = await getUserLocationIds(user.userId)
    if (allowedIds && (!schedule.locationId || !allowedIds.includes(schedule.locationId))) notFound()
  }

  // Resolve target assets: junction rows win, fall back to the legacy single assetId
  const targetAssets = schedule.assets.length > 0
    ? schedule.assets.map(a => a.asset)
    : (schedule.asset ? [schedule.asset] : [])

  // Query work orders generated by this specific PM schedule, falling back to the assets' PREVENTIVE work orders
  const workOrders = await prisma.workOrder.findMany({
    where: {
      OR: [
        { maintenanceScheduleId: schedule.id },
        ...(targetAssets.length > 0 ? [{ assetId: { in: targetAssets.map(a => a.id) }, type: 'PREVENTIVE' as const }] : []),
      ]
    },
    include: { assignedTo: { select: { name: true } } },
    orderBy: { createdAt: 'desc' },
    take: 20,
  })

  const days    = daysUntil(schedule.nextDueDate)
  const overdue = schedule.isActive && days < 0
  const canGenerate = schedule.isActive && days <= 0

  const targetName = targetAssets[0]?.name ?? schedule.location?.name ?? 'General'

  return (
    <div className="p-6 max-w-6xl mx-auto">
      <div className="mb-1">
        <Link href="/preventive-maintenance" className="text-sm text-gray-400 hover:text-gray-600">
          ← Back to PM schedules
        </Link>
      </div>
      <PageHeader
        title={schedule.title}
        subtitle={`${targetName} · Every ${schedule.interval > 1 ? `${schedule.interval} ` : ''}${freqLabels[schedule.frequency].toLowerCase()}`}
        action={
          canEdit ? (
            <div className="flex gap-2">
              <Link href={`/preventive-maintenance/${schedule.id}/edit`} className="btn-secondary text-sm">
                Edit schedule
              </Link>
              <PMCopyButton scheduleId={schedule.id} />
            </div>
          ) : undefined
        }
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left */}
        <div className="space-y-5">
          {/* Next due + generate */}
          <div className="bg-white rounded-xl border border-gray-200 p-5">
            <h2 className="font-semibold text-gray-900 text-sm mb-3">Next due date</h2>
            <p className={`text-2xl font-bold mb-1 ${overdue ? 'text-red-600' : 'text-gray-900'}`}>
              {fmt(schedule.nextDueDate)}
            </p>
            <p className={`text-sm mb-4 ${overdue ? 'text-red-500' : 'text-gray-400'}`}>
              {overdue
                ? `${Math.abs(days)} day${Math.abs(days) !== 1 ? 's' : ''} overdue`
                : days === 0
                ? 'Due today'
                : `In ${days} day${days !== 1 ? 's' : ''}`}
            </p>

            {canEdit && (
              <PMGenerateButton
                scheduleId={schedule.id}
                assetName={targetName}
                scheduleName={schedule.title}
                canGenerate={canGenerate}
                isOverdue={overdue}
              />
            )}
          </div>

          {/* Preview upcoming WOs */}
          {canEdit && schedule.schedulingHorizon > 1 && (
            <PMPreviewPanel scheduleId={schedule.id} />
          )}

          {/* Details */}
          <div className="bg-white rounded-xl border border-gray-200 p-5">
            <h2 className="font-semibold text-gray-900 text-sm mb-4">Schedule details</h2>
            <dl className="space-y-3">
              {[
                { label: 'Status',     value: (
                  <Badge label={schedule.isActive ? 'Active' : 'Inactive'} variant={schedule.isActive ? 'green' : 'gray'} />
                )},
                ...(targetAssets.length === 1 ? [
                  { label: 'Asset',      value: (
                    <Link href={`/assets/${targetAssets[0].id}`} className="text-blue-600 hover:underline text-xs">
                      {targetAssets[0].name}
                    </Link>
                  )},
                  { label: 'Asset code', value: targetAssets[0].assetCode ?? '—' },
                  { label: 'Location',   value: targetAssets[0].location?.name ?? '—' },
                  { label: 'Category',   value: targetAssets[0].category?.name ?? '—' },
                ] : []),
                ...(targetAssets.length > 1 ? [
                  { label: 'Target assets', value: (
                    <div className="flex flex-wrap gap-1 justify-end">
                      {targetAssets.map(a => (
                        <Link key={a.id} href={`/assets/${a.id}`} className="text-blue-600 hover:underline text-xs">
                          {a.name}
                        </Link>
                      ))}
                    </div>
                  )},
                  { label: 'Asset count', value: `${targetAssets.length} assets` },
                ] : []),
                ...(schedule.location ? [
                  { label: 'Location', value: schedule.location.name },
                  { label: 'Scope', value: schedule.locationScope === 'ALL_ASSETS' ? 'All Assets Checklist' : 'General Maintenance' },
                ] : []),
                { label: 'Frequency',  value: `Every ${schedule.interval > 1 ? `${schedule.interval} ` : ''}${freqLabels[schedule.frequency].toLowerCase()}` },
                { label: 'Trigger',    value: (
                  <Badge
                    label={schedule.triggerType === 'TIME_OR_METER' ? 'Time or Usage' : schedule.triggerType === 'METER' ? 'Meter' : 'Time'}
                    variant={schedule.triggerType === 'METER' ? 'yellow' : schedule.triggerType === 'TIME_OR_METER' ? 'orange' : 'gray'}
                  />
                )},
                { label: 'Behavior',   value: (
                  <Badge label={schedule.scheduleBehavior === 'FLOATING' ? 'Floating' : 'Fixed'} variant={schedule.scheduleBehavior === 'FLOATING' ? 'blue' : 'gray'} />
                )},
                ...(schedule.scheduleBehavior === 'FLOATING' && schedule.lastCompletedAt ? [
                  { label: 'Last completed', value: fmt(schedule.lastCompletedAt) },
                ] : []),
                ...(schedule.schedulingHorizon > 1 ? [
                  { label: 'Horizon', value: `${schedule.schedulingHorizon} WOs ahead` },
                ] : []),
                ...(schedule.startDateOffset > 0 ? [
                  { label: 'Start offset', value: `${schedule.startDateOffset} day${schedule.startDateOffset !== 1 ? 's' : ''} before due` },
                ] : []),
                { label: 'WO Priority', value: schedule.woPriority ?? 'Medium' },
                ...(schedule.woAssignedTo ? [
                  { label: 'WO Assignee', value: schedule.woAssignedTo.name },
                ] : []),
                ...(schedule.woTeam ? [
                  { label: 'WO Team', value: schedule.woTeam.name },
                ] : []),
                ...(schedule.woCategory ? [
                  { label: 'WO Category', value: schedule.woCategory.name },
                ] : []),
                { label: 'Task template', value: `${schedule.tasks.length} task${schedule.tasks.length !== 1 ? 's' : ''}` },
                { label: 'Created by', value: schedule.createdBy?.name ?? '—' },
                { label: 'Created',    value: fmt(schedule.createdAt) },
              ].map(row => (
                <div key={row.label} className="flex justify-between items-center gap-4">
                  <dt className="text-xs text-gray-400 flex-shrink-0">{row.label}</dt>
                  <dd className="text-xs text-gray-900 font-medium text-right">{row.value}</dd>
                </div>
              ))}
            </dl>
          </div>

          {/* Description */}
          {schedule.description && (
            <div className="bg-white rounded-xl border border-gray-200 p-5">
              <h2 className="font-semibold text-gray-900 text-sm mb-2">Description</h2>
              <p className="text-sm text-gray-600 leading-relaxed">{schedule.description}</p>
            </div>
          )}

          {/* Nested PM Tiers */}
          {schedule.nestedConfig && Array.isArray(schedule.nestedConfig) && (schedule.nestedConfig as any[]).length > 0 && (
            <div className="bg-white rounded-xl border border-gray-200 p-5">
              <h2 className="font-semibold text-gray-900 text-sm mb-3">Nested Maintenance Tiers</h2>
              <div className="space-y-2">
                {(schedule.nestedConfig as any[]).map((tier: any, i: number) => (
                  <div key={i} className="flex items-center gap-2 text-sm">
                    <Badge label={tier.enabled ? 'Active' : 'Disabled'} variant={tier.enabled ? 'green' : 'gray'} />
                    <span className="font-medium text-gray-800">{tier.label || `Tier ${i + 2}`}</span>
                    <span className="text-gray-500 text-xs">
                      Every {tier.interval > 1 ? `${tier.interval} ` : ''}{freqLabels[tier.frequency]?.toLowerCase()} · Run every {tier.runEvery} WO{tier.runEvery > 1 ? 's' : ''}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Task Template */}
          {schedule.tasks.length > 0 && (
            <div className="bg-white rounded-xl border border-gray-200 p-5">
              <h2 className="font-semibold text-gray-900 text-sm mb-1">
                Task Template
                <span className="ml-2 text-gray-400 font-normal">({schedule.tasks.length})</span>
              </h2>
              <p className="text-xs text-gray-400 mb-3">
                Copied onto generated work orders as subtasks.
              </p>
              <ol className="space-y-2">
                {schedule.tasks.map((task: any, i: number) => (
                  <li key={i} className="flex items-center gap-3 text-sm">
                    <span className="flex-shrink-0 w-6 h-6 rounded-full bg-emerald-50 text-emerald-700 text-xs font-bold flex items-center justify-center">
                      {i + 1}
                    </span>
                    <span className="flex-1 text-gray-800">{task.title}</span>
                    {task.assignedTo && (
                      <span className="text-xs text-gray-400 flex-shrink-0">→ {task.assignedTo.name}</span>
                    )}
                  </li>
                ))}
              </ol>
            </div>
          )}

          {/* Toggle active */}
          {canEdit && (
            <div className="bg-white rounded-xl border border-gray-200 p-5">
              <h2 className="font-semibold text-gray-900 text-sm mb-2">Schedule active</h2>
              <p className="text-xs text-gray-500 mb-3">
                {schedule.isActive
                  ? 'This schedule is active. Deactivating will stop new WOs from being generated.'
                  : 'This schedule is inactive. Activate to resume WO generation.'}
              </p>
              <PMToggleButton scheduleId={schedule.id} isActive={schedule.isActive} />
            </div>
          )}

          {/* Danger zone */}
          {user?.role === 'ADMIN' && (
            <div className="bg-white rounded-xl border border-red-100 p-5">
              <h2 className="font-semibold text-red-700 text-sm mb-2">Danger zone</h2>
              <p className="text-xs text-gray-500 mb-3">
                Deleting this preventive maintenance schedule will permanently remove it. Future work orders will not be generated automatically.
              </p>
              <DeletePMScheduleButton scheduleId={schedule.id} scheduleName={schedule.title} />
            </div>
          )}
        </div>

        {/* Right: generated WO history */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-xl border border-gray-200">
            <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100">
              <h2 className="font-semibold text-gray-900 text-sm">
                Generated work orders
                <span className="ml-2 text-gray-400 font-normal">({workOrders.length})</span>
              </h2>
            </div>
            {workOrders.length === 0 ? (
              <div className="py-16 text-center">
                <p className="text-sm text-gray-400">No work orders generated yet</p>
                {canGenerate && canEdit && (
                  <p className="text-xs text-gray-400 mt-1">Click "Generate work order" to create the first one</p>
                )}
              </div>
            ) : (
              <div className="divide-y divide-gray-50">
                {workOrders.map((wo: any) => (
                  <Link
                    key={wo.id}
                    href={`/work-orders/${wo.id}`}
                    className="flex items-center gap-4 px-5 py-3.5 hover:bg-gray-50 transition-colors"
                  >
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-gray-900 truncate">{wo.title}</p>
                      <p className="text-xs text-gray-400">
                        {wo.woNumber}{wo.assignedTo ? ` · ${wo.assignedTo.name}` : ''}
                        {wo.dueDate ? ` · Due ${fmt(wo.dueDate)}` : ''}
                        {wo.nestedLabel ? ` · ${wo.nestedLabel}` : ''}
                      </p>
                    </div>
                    <div className="flex gap-2 flex-shrink-0">
                      <Badge label={wo.priority} variant={priorityVariant(wo.priority)} />
                      <Badge label={woStatusLabels[wo.status]} variant={workOrderStatusVariant(wo.status)} />
                    </div>
                  </Link>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
